# Site Configuration
[site]
  title              = "Upstart" # Shared title for SEO and OpenGraph
  description        = "A highly customizable saas & startup astro theme built with Tailwind CSS and Astro Js" # Shared description for SEO and OpenGraph
  tagline            = "Saas & Startup Astro Js Theme"
  taglineSeparator   = "" # default is " - " 
  baseUrl            = "https://upstart-astro.netlify.app" # Base URL for the site and used in OpenGraph meta tags.
  logo               = "/images/logo.svg" # Path to the site's logo
  logoHoverAnimation = true # Enable or disable logo hover animation
  logoText           = "Upstart" # Text displayed next to the logo
  logoWidth          = "32px" # Width of the logo
  logoHeight         = "32px" # Height of the logo

  # Add a trailing slash at the end of URLs (e.g., https://example.com/, https://example.com/contact/)
  # Note: Manually restart your server when you change this value
  trailingSlash = true

  # Add your site logo in image path below and open your terminal and run "npm run generate-favicons" to generate favicons for different devices and platform (https://realfavicongenerator.net/checker)
  [site.favicon]
    path  = "/images/favicons" # favicon images path (No need to change it)
    image = "/images/logo.svg" # Add your site logo path here and follow upper instruction


# SEO Metadata
# Specific SEO configurations that complement the general site settings.
# -----------------------------------------------------------------------------------------------------------------------------------
[seo]
  author = "Getastrothemes"
  keywords = [
    "saas astro theme",
    "saas business astro theme",
    "startup astro theme",
  ] # SEO keywords
  robots = "index, follow" # Instructs search engines on how to crawl and index the pages.

  [seo.robotsTxt]
    enable = true # Enables or disables robots.txt file generation on site build
    disallow = [
      "/cdn-cgi/",
    ] # Disallow specific paths (e.g., "/_astro/", "/cdn-cgi/")

  [seo.sitemap]
    enable = true # Enables or disables sitemap generation on site build
    exclude = [
    ] # exclude all pages that include these folder names (e.g., "blog", "services")


# Different theme settings
# -----------------------------------------------------------------------------------------------------------------------------------
[settings]
  # If you change value of the following content folder, make sure to change the folder name also from
  # note: restart your server when you change this value
  # - "src/content" folder
  # - "src/[...lang]/pages" folder
  # - "src/content.config.ts" collections object
  blogFolder        = "blog" # Folder where blog posts are stored

  pagination   = 6 # Number of posts displayed on each page blog list page
  stickyHeader = true # Enables or disable sticky feature of header

  # documentation - https://formspree.io/ | https://formsubmit.co/ | https://docs.netlify.com/forms/setup/
  # Form action URL for the contact form (For more settings related to form see "src/content/sections/contact-section.md")
  contactFormAction = "https://formsubmit.co/your_form_submission_receive_email" # https://formspree.io/f/your_form_id | https://formsubmit.co/your_form_submission_receive_email | "/"

  # formspree | formsubmit.co | netlify (default is formsubmit.co) 
  contactFormProvider = "formsubmit.co"

  footerDescription = "" # Check src/i18n/en.json and src/i18n/fr.json for changing the footer description in different languages or directly add value here if you are not using internationalization feature

  # For changing footer description and footer copyright in different languages see src/i18n/en.json and src/i18n/fr.json
  # We kindly appreciate it if you retain the theme copyright. Thank you for supporting Getastrothemes!
  [settings.copyright]
    enable = true
    text   = "" # Check src/i18n/en.json and src/i18n/fr.json for changing the copyright text in different languages or directly add value here if you are not using internationalization feature

  # Mailchimp Subscription Form located in footer
  [settings.subscription]
    enable     = true # Enables or disable the subscription form
    title      = "" # Check src/i18n/en.json and src/i18n/fr.json for changing the title in different languages or directly add value here if you are not using internationalization feature
    formAction = "https://gmail.us11.list-manage.com/subscribe/post?u=d870b06d86c16269e4b1f9b39&amp;id=12cf0c6ac2&amp;f_id=007e61e1f0"

  # Multilingual settings (check src/config/language.json for changing the languages)
  # NOTE: Manually restart your server when you change the following multilingual table values
  [settings.multilingual]
    # Set `enable` to `true` for enabling the multilingual feature or `false` for disabling it.
    # Run `npm run remove-multilingual` for removing multilingual content files after disabling the feature.
    enable               = true
    defaultLanguage      = "en"
    disableLanguages     = [] # List of languages to disable (eg: ["fr", "es"])
    showDefaultLangInUrl = false # Show default language in URL (eg: https://getastrothemes.com/en/)

  # Navigation Button In Header
  [settings.navigationButton]
    enable = true
    label  = "" # Check src/i18n/en.json and src/i18n/fr.json for changing the navigation button label in different languages or directly add value here if you are not using internationalization feature
    url    = "/contact/"

  [settings.markup.tableOfContents]
    enable     = true
    expanded   = true # whether to expand the table of contents by default
    endLevel   = 5
    ordered    = false
    startLevel = 1


# OpenGraph Metadata
# Specific OpenGraph settings, using values from the [site] section where possible.
# -----------------------------------------------------------------------------------------------------------------------------------
[opengraph]
  image       = "/images/og-image.jpg" # Image used in OpenGraph previews
  ogLocale    = "en_US" # Locale setting for OpenGraph
  ogType      = "website" # Type of content for OpenGraph protocol
  twitter     = "" # Twitter handle for Twitter Card meta tags
  twitterCard = "summary_large_image" # Type of Twitter Card to use in social sharing

# [head] (Add custom scripts, stylesheets, and meta tags to be rendered in the <head> section of the page)
# -----------------------------------------------------------------------------------------------------------------------------------
[head]
  content = """
  <!-- You can easily add this type of tracking code by updating the `config.toml` file -->
  <script defer src="/umami.is.js" data-website-id=""></script>
  """
